<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Start Shopping</name>
   <tag></tag>
   <elementGuidId>6da153f6-e8e6-4b2a-8b9a-b17dce8023ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='start-shopping-button']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#start-shopping-button > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6361f605-3891-464f-962f-912edeb5e474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop</value>
      <webElementGuid>0e07dc73-aa85-4d72-9e5d-cf386c184bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Start Shopping →</value>
      <webElementGuid>c43394cd-2eb6-4d46-86ed-42ac53a195ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-shopping-button&quot;)/a[1]</value>
      <webElementGuid>ea4571af-5d18-4734-83ed-9a0cb67fe3ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='start-shopping-button']/a</value>
      <webElementGuid>092ad170-f85b-499f-b320-a90cd0e2f5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::a[2]</value>
      <webElementGuid>e7d0f944-04a4-4055-9336-ea7d42fe9726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Items Right Now!!!'])[1]/preceding::a[1]</value>
      <webElementGuid>4e71c83f-eced-42db-967e-19a522fd6c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start Shopping']/parent::*</value>
      <webElementGuid>615380de-98aa-40aa-9ba7-64f1d984db5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/shop')])[2]</value>
      <webElementGuid>7cc150cd-525b-4708-8e39-4e00deaca839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a</value>
      <webElementGuid>229baa04-7086-40b5-b100-28a9cee16275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop' and (text() = 'Start Shopping →' or . = 'Start Shopping →')]</value>
      <webElementGuid>557acf7b-ab8d-4653-95cc-48c1e0ded222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
