<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log In</name>
   <tag></tag>
   <elementGuidId>d3f0f812-c212-4fea-808f-8c30a267d2ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal-log-in-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-log-in-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a281711-efe4-47e6-a4ea-97d5f84f6e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-semibold rounded-md shadow-md p-2 transition ease-out duration-500 transform hover:-translate-y-0.5  hover:scale-110 hover:opacity-80 whitespace-nowrap bg-secondary text-white w-1/4 mr-4</value>
      <webElementGuid>945164eb-0908-419a-b416-0dcf45fd0721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-log-in-button</value>
      <webElementGuid>f748768a-e64b-4d94-88ba-1033e0d0a2bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>386f6d9e-4229-4505-87ea-3bf4181f463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>9c38b166-f3da-4d59-86c5-dd0b9a8d4c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-log-in-button&quot;)</value>
      <webElementGuid>4a51a2dc-8913-4c2f-8bd8-1675be070664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal-log-in-button']</value>
      <webElementGuid>ff93122b-0295-4d1b-9127-9f4468279b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-modal']/span/button[2]</value>
      <webElementGuid>20a7470f-3120-4c5c-84b6-39e77a5f6b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>96f4a245-64e1-44f0-b915-f945dc2c2dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree to the terms of service'])[1]/following::button[2]</value>
      <webElementGuid>6c666844-772f-4196-8d00-65266f406745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'modal-log-in-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d42fe1b8-33dd-4e5d-99a1-bda02975692c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button[2]</value>
      <webElementGuid>857b8ad6-5d9a-465d-8a52-223d3e077306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modal-log-in-button' and @type = 'button' and (text() = 'Log In' or . = 'Log In')]</value>
      <webElementGuid>b5812725-4103-4c81-8921-b2c4fcf3f428</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
