<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>f0244346-2873-43af-8604-ba76ff4184df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='modal-yes-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-yes-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6807e0d8-b182-4a21-b7ae-48a7b0a36a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-semibold rounded-md shadow-md p-2 transition ease-out duration-500 transform hover:-translate-y-0.5  hover:scale-110 hover:opacity-80 whitespace-nowrap bg-secondary text-white w-1/4 mr-4</value>
      <webElementGuid>28954a1f-566f-446b-996d-e1e630019a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-yes-button</value>
      <webElementGuid>c456ff51-09be-40e8-95e5-ee6b0830abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5030f771-fc40-4fa5-b326-da8a7b2fc02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>72f6fc9d-b7c7-433f-88d5-1687d445cb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-yes-button&quot;)</value>
      <webElementGuid>07e8cd28-37b7-4623-ad72-2a40834f2e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='modal-yes-button']</value>
      <webElementGuid>d511e4ae-f93e-40a0-bb08-abecb21f1fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='logout-modal']/span/button[2]</value>
      <webElementGuid>52423b80-ece5-44ba-8f9e-78051b5fe39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>7f85908b-7843-4ba9-b4ae-49f33b3744a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure that you want to logout?'])[1]/following::button[2]</value>
      <webElementGuid>d4beeeb7-78df-433d-987e-36df510b785b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'modal-yes-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>85673bb6-c753-47c9-9998-121433075750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>f8a1e11d-9fde-4de2-929e-89208d906763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/button[2]</value>
      <webElementGuid>e6989dcc-7b04-4142-b742-31e0f1882835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'modal-yes-button' and @type = 'button' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>8b009d9b-b862-4454-8698-894b77ddaa63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
