<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_surname</name>
   <tag></tag>
   <elementGuidId>6eb86842-29d3-48e7-9622-3a8c2fde571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='surname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#surname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>327ee548-a57c-4caa-9356-1dad92f2ef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>surname</value>
      <webElementGuid>c108f93d-f086-4762-ba58-b2f557ac987a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-base font-semibold rounded-md shadow-md p-2 border-2 hover:border-gray-400 hover:border-black border-gray-300</value>
      <webElementGuid>0bcbc445-71bc-423b-9ce6-df33b40c39ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surname&quot;)</value>
      <webElementGuid>7a0cae5c-1cc0-4178-94b4-04fe7730ec22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='surname']</value>
      <webElementGuid>a5cab2c8-5497-4631-a1e2-265b312ffb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/form/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>fb170855-f151-44dd-af89-4afe300deb6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>50a1bd92-6ebe-4283-a649-a27d8d2115df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'surname']</value>
      <webElementGuid>c278b3e5-e1fb-41ce-bffd-5eb6ef4fcfdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
