<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__forename</name>
   <tag></tag>
   <elementGuidId>dc3c870f-0a45-44c0-9e6c-84ca8faa9b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='forename']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#forename</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb704fc0-3eea-4984-a45b-65175d641ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>forename</value>
      <webElementGuid>9a309ea4-9537-4e0f-9e8e-db42bdb88193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-base font-semibold rounded-md shadow-md p-2 border-2 hover:border-gray-400 hover:border-black border-gray-300</value>
      <webElementGuid>b390fdcc-336c-45b6-867e-a57f7c9c8dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;forename&quot;)</value>
      <webElementGuid>ee9aab98-3c54-4240-8fb9-084234797090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='forename']</value>
      <webElementGuid>e809b7a4-0531-4eaf-80ab-295f32843e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>bd074472-68d3-47fd-96e5-ee3dbf6d0c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>cf4c89f3-6983-4128-84e5-6e449d0e449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'forename']</value>
      <webElementGuid>fcf46344-b9a4-46ca-b7f7-91c02f4b5b5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
